kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.14.2-jdk21-jammy
    commands:
      - gradle test
  - name: publish
    image: gradle:8.14.2-jdk21-jammy
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - apt-get update && apt-get install -y curl
      - gradle execJar publish
      - "export CI_BUILD=$(gradle properties | grep 'version:' | sed 's/version: //') && \
      ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/package-dependency ./build/libs/package-dependency ./build/libs/package-dependency-exec.jar"
    when:
      ref:
        - refs/heads/master
