name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Artefacts
        env:
          ARTEFACTS_USER: ${{ secrets.ARTEFACTS_USER }}
          ARTEFACTS_PASSWORD: ${{ secrets.ARTEFACTS_PASSWORD }}
          CI_BUILD: 1.0.5
        run: |
          ./gradlew publish execJar
          ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/package-dependency ./build/libs/package-dependency ./build/libs/package-dependency-exec.jar
